if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE and OUTPUT_FILE are required")
endif()

file(READ "${INPUT_FILE}" KERNEL_SOURCE)
string(REPLACE "\r\n" "\n" KERNEL_SOURCE "${KERNEL_SOURCE}")
string(REPLACE "\r" "\n" KERNEL_SOURCE "${KERNEL_SOURCE}")
string(REPLACE "\n" ")\"\nR\"(" KERNEL_SOURCE "${KERNEL_SOURCE}")
file(WRITE "${OUTPUT_FILE}" "R\"(${KERNEL_SOURCE})\"\n")
